<?php

$lang = [
    'home'                 => '首页',
    'memcp'                => '个人',
    'shop'                 => '商店',
    'pc'                   => 'PC',
    'daycare'              => '饲育屋',
    'shelter'              => '孤儿院',
    'adventure'            => '冒险',
    'ranking'              => '排行榜',
    'forum'                => '论坛',
    'trainer_entrance'     => '训练师入口',
    'current_time'         => '目前时间',
    'browser_advice'       => '请使用现代浏览器（如<a href="http://www.google.com/chrome" target="_blank">谷歌浏览器</a>）访问以取得最佳效果。',
    'app_name'             => '口袋大冒险',
    'app_description'      => '口袋妖怪在线养成冒险系统',
    'app_keywords'         => '口袋妖怪,神奇宝贝,精灵宝可梦,宠物小精灵,口袋大冒险,养成,冒险,新养成,口袋大学城',
    'world_stats'          => '世界情报',
    'horde_info'           => '精灵情报',
    'newest_updates'       => '最新动态',
    'outstanding_trainers' => '优秀训练师',
    'username'             => '用户名',
    'password'             => '密码',
    'sign_in'              => '登入',
    'sign_up'              => '注册',
    'memory_usage'         => '内存耗用',
    'level'                => '等级',
    'pokedex'              => '图鉴',
    'currency'             => '弹珠',
    'online_total'         => '在线人数',
    'trainer_total'        => '训练师和',
    'pokemon_total'        => '精灵总数',
    'shiny_total'          => '闪光总数',
    'unknown' => '未知',
    'data_move_types' => ['', '火', '水', '草', '电', '普', '格', '飞', '虫', '毒', '岩', '地', '钢', '冰', '超', '恶', '鬼', '龙', '妖'],
    'data_move_classes' => ['变化', '物理', '特殊'],
    'data_egg_groups' => ['', '陆上', '昆虫', '飞行', '怪兽', '妖精', '人形', '矿物', '植物', '水中1', '水中2', '水中3', '飞龙', '不定形', '百变怪', '未发现'],
    'data_item_types' => ['', '球类', '进化石', '携带道具', '药物'],
];